SELECT 'OLDEST' as TYPE, NAME, MIN(WORKER.BIRTHDAY) as BIRTHDAY from WORKER
group by NAME
HAVING BIRTHDAY = (SELECT MIN(WORKER.BIRTHDAY) as BIRTHDAY from WORKER)
UNION
SELECT 'YOUNGEST' as TYPE, NAME, MAX(WORKER.BIRTHDAY) as BIRTHDAY from WORKER
group by NAME
HAVING BIRTHDAY = (SELECT MAX(WORKER.BIRTHDAY) as BIRTHDAY from WORKER);